#!/bin/sh
# -*- sh -*-
# vim: set syntax=sh
# code: language=shellscript

# Copyright (c) 2020 Michael Federczuk
# SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

readonly input_file="${1:-example_input}"

readonly timestamp=$(head -n1 "$input_file")
readonly bus_ids=$(head -n2 "$input_file" | tail -n1)

i=1
while bus_id=$(printf %s "$bus_ids" | cut -d, -f$i) && [ -n "$bus_id" ]; do
	i=$(echo $i + 1 | bc)

	if [ "$bus_id" = x ]; then
		bus_times=${bus_times:+$bus_times,}x
		continue
	fi

	time=$(echo "$timestamp / $bus_id * $bus_id + $bus_id" | bc)
	bus_times=${bus_times:+$bus_times,}$time
done

least_bus_i=-1
least_time=999999999
i=1
while tmp=$(printf %s "$bus_times" | cut -d, -f$i) && [ -n "$tmp" ]; do
	if [ "$tmp" != x ] && [ "$tmp" -lt $least_time ]; then
		least_time=$tmp
		least_bus_i=$i
	fi

	i=$(echo $i + 1 | bc)
done

least_bus_id=$(printf %s "$bus_ids" | cut -d, -f$least_bus_i)
echo "($least_time - $timestamp) * $least_bus_id" | bc
