#!/bin/sh
# -*- sh -*-
# vim: set syntax=sh
# code: language=shellscript

# Copyright (c) 2020 Michael Federczuk
# SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

# just a warning: it took ~30min for this script to find the correct number with the actual puzzle input
# god i'm regretting using sh for today

readonly input_file="${1:-example_input}"
if [ "$input_file" != 'example_input' ]; then
	readonly preamble_length=25
else
	readonly preamble_length=5
fi

add() {
	echo "$1" + "$2" | bc
}

line=$(add $preamble_length 1) # starting at line $preamble_length + 1

get_input_file_line() {
	head -n"$1" "$input_file" | tail -n1 # creative way to get the nth line of a file
}
increment() {
	add "$1" 1
}

while true; do
	nr=$(get_input_file_line "$line")

	found=false
	i=1
	while [ $i -lt "$(add $preamble_length 1)" ]; do
		j=1
		while [ $j -lt "$(add $preamble_length 1)" ]; do
			nr1=$(get_input_file_line "$(add "$line" -$i)")
			nr2=$(get_input_file_line "$(add "$line" -$j)")

			if [ "$(add "$nr1" "$nr2")" = "$nr" ]; then
				found=true
				break 2
			fi

			j=$(increment $j)
		done

		i=$(increment $i)
	done

	if ! $found; then
		echo "$nr"
		exit
	fi

	line=$(increment "$line")
done
