#!/bin/bash
# -*- sh -*-
# vim: set syntax=sh
# code: language=shellscript

# Copyright (c) 2020 Michael Federczuk
# SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

readonly input_file_path="${1:-example_input}"

nrs=()

while read -rs line; do
	# shellcheck disable=2206
	nrs+=($line)
done < "$input_file_path"

readonly l=${#nrs[@]}

for ((i = 0; i < l; ++i)); do
	for ((j = 0; j < l; ++j)); do
		for ((k = 0; k < l; k++)); do
			if ((nrs[i] + nrs[j] + nrs[k] == 2020)); then
				echo $((nrs[i] * nrs[j] * nrs[k]))
				exit
			fi
		done
	done
done

exit 1
