#!/bin/sh
# -*- sh -*-
# vim: set syntax=sh
# code: language=shellscript

# Copyright (c) 2021 Michael Federczuk
# SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

set -o errexit

root_dir_path="$(dirname -- "$0")"
root_dir_path="$(realpath -s --relative-to=. -- "$root_dir_path")"
readonly root_dir_path

for dir in "$root_dir_path/day"[01][0-9]; do
	make -C "$dir" clean
	echo >&2
done
