#!/bin/bash
# -*- sh -*-
# vim: set syntax=sh
# code: language=shellscript

# Advent of Code 2020 - Day 1 - Part 2
# Copyright (C) 2020  Michael Federczuk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

readonly input_file_path="${1:-example_input}"

nrs=()

while read -rs line; do
	# shellcheck disable=2206
	nrs+=($line)
done < "$input_file_path"

readonly l=${#nrs[@]}

for ((i = 0; i < l; ++i)); do
	for ((j = 0; j < l; ++j)); do
		for ((k = 0; k < l; k++)); do
			if ((nrs[i] + nrs[j] + nrs[k] == 2020)); then
				echo $((nrs[i] * nrs[j] * nrs[k]))
				exit
			fi
		done
	done
done

exit 1
